{% set name = "ChiantiPy" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chianti-atomic/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f92e577249bceb6cd33df5429b0dc8c66276825ffa9af9356f97f4aa91a2fa0e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - ipyparallel
    - matplotlib
    - pyqt

test:
  requires:
    - python {{ python_min }}
  imports:
    - ChiantiPy

about:
  home: https://github.com/chianti-atomic/ChiantiPy
  summary: a Python interface to the CHIANTI atomic database for astrophysical spectroscopy
  license: ISC
  license_file: licenses/LICENSE
  description: |
    ChiantiPy is the Python interface to the CHIANTI atomic database for astrophysical 
    spectroscopy. It provides the capability to calculate the emission line and 
    continuum spectrum of an optically thin plasma based on the data in the 
    CHIANTI database.
  doc_url: https://chiantipy.readthedocs.io/en/latest/
  dev_url: https://github.com/chianti-atomic/ChiantiPy

extra:
  recipe-maintainers:
    - epassaro
